### ISSUE TITLE
Fix geolocation errors on driver app on staging server

### ISSUE THREAD

**Issue by john** [john/drive.vote#1003]
It's saying it can't find the address when you try to schedule a ride, it's probably an issue with the Geolocation API keys.

**Comment by smarbin** [comment]
From here https://intense-coast-67101.herokuapp.com/rides I seem to always get this message: “Error creating ride - Address for pickup could not be found” 

But from the specific SF Ride Zone URL https://intense-coast-67101.herokuapp.com/ride/san_francisco I am able to schedule with some addresses, but not others e.g. 1) 100 Larkin St. is okay.  2) 1 Dr Carlton B Goodlett Pl gives error 3) 1229 Pearl St. (alameda) gives error
![screen shot 2018-09-28 at 1 28 36 pm](https://user-images.githubusercontent.com/20249846/46231985-8f94d400-c322-11e8-8887-4733e6bdbc7d.png)
![screen shot 2018-09-28 at 1 26 44 pm](https://user-images.githubusercontent.com/20249846/46231992-91f72e00-c322-11e8-8e58-f4988677b9a0.png)

**Comment by john** [comment]
The Google API key on both prod and staging needed to be updated, once done both work with all addresses above, and others I tested. This also fixed the auto complete on the 'What city and state?' field.
