### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by smarbin** [john/drive.vote#1004]
Could it be because I logged in as a DRIVER in the same Chrome profile window where I'm am logged in as an ADMIN? I haven't seen this one before. 

![www drive vote_driving pixel 2](https://user-images.githubusercontent.com/20249846/46239893-4198c400-c354-11e8-84f1-1e35ac2e3dd7.png)

**Comment by john** [comment]
I'm gonna guess things just got confused with your logged in twice. Which you actually weren't--you can only be logged in once, so logging in a second time logged you out of the initial section.

If you *don't* do that--log in twice in the same profile window--is this repeatable? If you can't repeat without doing unnatural things, I'd vote to close this.

**Comment by jillh510** [comment]
@smarbin has this bug ever been seen since?

**Comment by smarbin** [comment]
OK - I was able to replicate it, and seems like very edge case. I think we can close it. 

Basically, when I am logged in as a driver in one window and an admin in another (both in the same chrome profile), if I log out in the admin window... then go to the driver window, I get a “oops something went wrong" error in the driver app. closing that oops message I then get this !Syntax error. But basically a refresh just makes me log in again so doesn't seem to cause any harm.
