### ISSUE TITLE
Driver app doesn't work on desktop Firefox

### ISSUE THREAD

**Issue by john** [john/drive.vote#1007]
Haven't tested with mobile Firefox, but see screenshot for the blank page you get on desktop Firefox. This isn't critical, but if it's an easy fix, it would be useful for testing.

<img width="642" alt="screen shot 2018-09-30 at 10 32 52 am" src="https://user-images.githubusercontent.com/1668/46260551-45376280-c49c-11e8-9fcd-b2e9a4b7b19f.png">

**Comment by mcamis** [comment]
@john are you getting any console errors? This is working for me locally on MacOS 10.13 / Firefox 62.0.2

**Comment by john** [comment]
low priority and may be working anyway, so closing
