### ISSUE TITLE
Update/Remove text on confirmation screen

### ISSUE THREAD

**Issue by smarbin** [john/drive.vote#1014]
Confirm which email we are using for support. I think it's the hello@drive.vote but this confirmation screen shows two emails. 

![screen shot 2018-10-01 at 3 40 09 pm](https://user-images.githubusercontent.com/20249846/46321498-74cb9500-c598-11e8-91cc-c69352dd7c7f.png)

**Comment by john** [comment]
That email will be set for each RZ and should be a distribution list going to admins and dispatchers, so I think this is ok to keep as-is. Please feel free to re-open if it needs discussion, but I'm going to close.
