### ISSUE TITLE
Update drive.vote website 

### ISSUE THREAD

**Issue by smarbin** [john/drive.vote#1027]
Once we have confirmed our final Ride Zones, we need to add text and links to drive.vote:
- Add names of Ride Zones to the main page
- Add links to Driver and Rider forms for each of those zones
- Add text about this being a pilot and what to do if you aren't in one of those zones

Per conversation with @bradyk - we may want to update other text on that page as well.

**Comment by jillh510** [comment]
Also: update the page at https://www.drive.vote/about?locale=en, "Can my campaign use it?" to point people at https://ragtag.org/drive-the-vote rather than hello@drive.vote

**Comment by john** [comment]
Get video on Vimeo first, then include in page update, per #1052

**Comment by dryan** [comment]
The video part of this is done
