### ISSUE TITLE
Make sure rides on dispatcher rides page link to the... rides... so dispatchers can assign them

### ISSUE THREAD

**Issue by john** [john/drive.vote#1037]

**Comment by murdzaj** [comment]
@john it should be obvious to me but it isn't. What is the view/URL it should link to?

**Comment by john** [comment]
Add 'Edit' link next to 'Archive' here:
http://localhost:3000/dispatch/orlando/rides

Should go to something like this:
http://localhost:3000/admin/rides/271/edit
but with this url: /dispatch/orlando/rides/271/edit

the form can live under /views/dispatch/rides (share when possible), but the controller code needs to be DRY'd up pretty bad--there are currently 2 ride controllers (admin/ and /), and ride-related code also in app/controllers/admin/ride_uploads. Centralize CRUD and move what you can to the model.
