### ISSUE TITLE
New Video: Post to Vimeo and update on drive.vote homepage

### ISSUE THREAD

**Issue by smarbin** [john/drive.vote#1052]
Post to Vimeo and update on drive.vote homepage

Updated video link here:
https://www.dropbox.com/s/fjh7zptk0kr27el/DTV%202018%20WEB%20v2%201022218.mov?dl=0

**Comment by john** [comment]
When on Vimeo, include in rest of homepage update: #1027

**Comment by dryan** [comment]
any objection to having this as an unlisted YouTube video?

**Comment by dryan** [comment]
Closed by #1073
