### ISSUE TITLE
"Help" Fly-out still refers to Nomad

### ISSUE THREAD

**Issue by SquadronROE** [john/drive.vote#1081]
The Help flyout on https://staging.drive.vote/driving refers to "Nomad", which sounds like a product name and may be confusing to drivers. Could we remove this word entirely?

**Comment by jillh510** [comment]
Ugh it's worse than that......the article in the fly-out really is about a different project called Nomad, probably getting picked up because of the word "driving" in the article title. Will look into making sure the widget only picks up articles tagged "drive the vote".

**Comment by jillh510** [comment]
Can we set the widget in DtV to look for articles with the label 'drive the vote' based on the instructions here: https://developer.zendesk.com/embeddables/docs/widget/api#ze.sethelpcentersuggestions

**Comment by dryan** [comment]
Fixed by #1089
