### ISSUE TITLE
Download all unassigned drivers in a CSV

### ISSUE THREAD

**Issue by john** [john/drive.vote#1097]

**Comment by john** [comment]
Select
  u.id, u.name, u.email, u.phone_number, u.description
FROM
  users u INNER JOIN users_roles ur
  ON u.id=ur.user_id
WHERE
  ur.role_id=
    (SELECT id FROM roles WHERE name='unassigned_driver' AND resource_type='RideZone' AND resource_id =(SELECT id FROM ride_zones WHERE slug = 'ca-25'))
ORDER BY u.id ASC

[ca-25-unapproved-drivers.csv.txt](https://github.com/john/drive.vote/files/2545604/ca-25-unapproved-drivers.csv.txt)

**Comment by dryan** [comment]
I removed the CSVs since they've got PII. Sharing with the appropriate folks.
