### ISSUE TITLE
Remove limits on what states users can be from

### ISSUE THREAD

**Issue by john** [john/drive.vote#1100]
Background: in 2016 after we switched from peer-to-peer to local partners, we still had people signing up from all over the place, so I added a 'permissible states' requirement, which is still there, but expanded to include existing and likely ride zone states.

Problem: that check relies on the state being a two-letter abbreviation. We're removing that, but if the state is 'Texas,' it then triggers the not in permissible state validation.

Solution: remove the `validate :permissible_zip` check in user.rb

At the same time I'll remove the `validates :state, length: { maximum: 2 }` check on user.rb, so it matches the change made to ride.rb

**Comment by dryan** [comment]
👍

**Comment by john** [comment]
Removed relevant methods and specs. Specs passed, and I smoke tested locally--using the full strings "California" and "Texas" both work on local ride zones for those areas, and both geocode correctly.
