### ISSUE TITLE
AWSELB version disclosure

### ISSUE THREAD

**Issue by engerm** [john/drive.vote#506]
Description:

A malformed request exposes the AWSELB version information:
400 Bad Request
awselb/2.0

NOTE: This poses a potential security issue

Version:
unknown
https://dev.drive.vote

Steps:
Load the following URL as an unauthenticated user:
https://dev.drive.vote/%E2%x80%AE

Actual Results:
- URL loads and exposes the AWSELB version

Expected Results:
1) URL would not expose the AWSELB version
2) User would get a DtV template informing them of the error

**Comment by Gowthamcloud** [comment]
As its version disclourse is captured over the cache it will help attacker to know the my server hosting environment so its potential risk can someone help to find workaround please
