### ISSUE TITLE
Dispatcher should not be able to modify driver after ride is complete

### ISSUE THREAD

**Issue by engerm** [john/drive.vote#593]
Description:

After a ride is complete, the dispatcher should not be able to change the driver; currently the dispatcher can. There should be a record of who drover the rider/voter. 

NOTE: This data was reused but the initial account using that data was QA cleared and Destroyed before reusing it to schedule a new ride.

Version:
unknown
https://dev.drive.vote

Steps:

Schedule a ride using information that is not being used elsewhere in the system

Complete a ride - assign to driver; driver select, accept, pick up and complete.

Log in DtV as a user that has access to dispatch

Navigate to dispatch app.

Click Inactive tab

Locate recently created ride request; click on voter/rider.

Change driver

Actual Results:
- The driver can be changed after a ride is complete

Expected Results:
1) The driver should not be able to be changed after a ride is complete.
2) The driver select/drop-drop should be disabled.

**Comment by john** [comment]
We should only do this if a ride can be changed back to 'uncomplete', otherwise a ride inadvertently completed ends up in limbo, unable to be recovered.

**Comment by john** [comment]
Decided to just keep logs after election for a week.
