### ISSUE TITLE
During a ride, mouseover should bounce the driver pin, not the voter pin

### ISSUE THREAD

**Issue by jillh510** [john/drive.vote#808]
Steps to reproduce:
- Have a driver pick up a voter
- As a dispatcher, look at the "Has Driver" tab
- Hover the mouse over the name of the voter who just got picked up

Expected result: The pale blue pin for the driver should bounce
Actual result: A dark blue voter pin appears on top of the driver pin, and the voter pin bounces.

**Comment by dryan** [comment]
Outcome from the bug council: the "Driving" icon that currently exists should represent *both* the rider and the driver while a voter is in the car. Additionally, we need to rework all 8 icons to be more visually distinctive and a11y friendly.
