### ISSUE TITLE
Missing cancellation notification

### ISSUE THREAD

**Issue by wboykinm** [john/drive.vote#819]
1. Maia requested a ride and confirmed
2. Ian (using the driver app) took the ride request
3. Ian cancelled
4. No cancellation message was sent
5. Ride remains unassigned.

![](https://www.dropbox.com/s/9ekwjqjg6qrqepg/Screenshot%202016-11-07%2021.29.40.png?dl=1)

(not to be confused with #814, which is also visible here.)

**Comment by jillh510** [comment]
this might be fixed; please test before coding!

**Comment by cgrayson** [comment]
To my rookie eyes this looks like it works. I also entered an email address for my test rider; I didn't get an email notification, though I wasn't sure if I was supposed to. But SMS, yes: 

<img width="307" alt="screen shot 2018-10-01 at 8 14 42 pm" src="https://user-images.githubusercontent.com/5596/46324006-dac71500-c5b6-11e8-9ab3-abd0ade873d1.png">

**Comment by dryan** [comment]
@john can we close this out?

**Comment by wboykinm** [comment]
(I reported this sucker on someone else's behalf back in '16; apologies I can't reproduce or test)

**Comment by cgrayson** [comment]
Calling this closed; easy enough to re-open if we see it again. 😄
