### ISSUE TITLE
Driver app should have an already voted button

### ISSUE THREAD

**Issue by engerm** [john/drive.vote#838]

**Comment by john** [comment]
Can we just put the text 'Cancelling a ride will make it available to other drivers' under the 'Cancel Pick Up' button, similar to the explanatory text under 'Archive Ride'?

**Comment by john** [comment]
@mcamis can this be closed?

**Comment by mcamis** [comment]
@john let's leave this open to track the (small-ish amount of) work needed to re-apply these changes, unfortunately it can't just be rebased or merged onto the current version of master.
