### ISSUE TITLE
Driver App v2 Braindump

### ISSUE THREAD

**Issue by mcamis** [john/drive.vote#876]
An in-progress wishlist for 2017:

- General refactoring to remove popsicle sticks and glue
  - Set prop types
  - Unit testing!
  - Research Immutable.js
- Setup as a Progressive Web App
  - manifest.json
  - offline service worker
  - investigate background service worker for location check-ins
- Improve styling / 'app'-ness
  - Switch to flexbox
  - Add sounds
  - Add animations
- Investigate separate build process for driving app; speed/network concerns are much tighter than dispatch

**Comment by john** [comment]
@mcamis moving this to icebox since it's more like great ideas for post-midterms.
