### ISSUE TITLE
Enhancement: ability for Super or Zone Admin to manually change driver status

### ISSUE THREAD

**Issue by engerm** [john/drive.vote#880]
This is an enhancement request for Super Admins or Zone Admins to manually update the status of driver to any status.

This request is a result of drivers getting in weird statuses during use of the app. Allowing a Super Admin or Zone Admin to change the driver's status will better help keep drivers in an active state to allow drivers to focus on driving.

**Comment by cgrayson** [comment]
Poking around a bit in the app and the code, I'm not sure I understand exactly what this needs. I don't see an explicit `status` for drivers. And if it means to manually change the status of a `Ride`, I think that can be done using the edit link on the [Rides page](http://localhost:3000/admin/rides).

**Comment by dryan** [comment]
@john can you confirm? I don't see status as a field for drivers in the schema so I presume their status is derived from a ride.

**Comment by cgrayson** [comment]
I wanted to add some more info here that John gave in a Slack discussion earlier, but hadn't gotten to it yet.

> in addition to what it says in the ticket, another use case is a driver goes off-duty, but doesn’t check out of the app

> I think it would be accessible to admins and dispatchers, and best go here, in a new column, if we can fit it in (right now the red and blue dots next to the driver name indicate status--blue is on-duty, red is off, i think the car icon means they’re mid-ride):

<img width="1043" alt="screen_shot_2018-10-09_at_11 36 52_am" src="https://user-images.githubusercontent.com/5596/46700823-7bcf5480-cbe3-11e8-889c-8131d1bfa7d8.png">

> May not be ideal, but you can see [if a driver has an active or open ride in `user.rb`](https://github.com/john/drive.vote/blob/master/app/models/user.rb#L206-L212). You can also look at the driving_controller, the [`status_data()` method](https://github.com/john/drive.vote/blob/master/app/controllers/driving_controller.rb#L138), which is used by the driving app & tells it info about the driver.
