### ISSUE TITLE
Conversation - change "Archive" to "Cancel"

### ISSUE THREAD

**Issue by engerm** [john/drive.vote#883]
**Description**

The "Archive" button does not accurately reflect the functionality of the button.

This is a request to change the button form Archive to Cancel Ride.

**Version**
unknown
https://dev.drive.vote

**Steps**

log in as dispatcher

open conversation

**Actual Results**
- button is labeled "Archive"

**Expected Results**
- button would be labeled "Cancel Ride"

**Comment by jamesarosen** [comment]
There's [already a "Cancel ride" button](https://github.com/john/drive.vote/blob/a0f8ab9b536b46a0c27fa11af9ffec6599c458a8/app/javascript/driving/components/ActiveRide.js#L76-L85). It looks to me like "cancel" is meant to put a not-yet-finished ride back into the pool, while "archive" is meant to remove it from view.

**Comment by john** [comment]
@jamesarosen this needs further clarification I think, but just went through this, and the 'cancel' button is meant to basically entirely remove a ride from the system, without putting it back in the pool. The driver becomes unassigned and can pick someone else up.

To try to make more clear in the UI I relabelled it "Cancel Ride," with confirmation text that makes it clear it's not put back in the pool. Also switched to a 'warning' style, and moved the button away from the 'x' to close the modal, it seemed they could be confused.
