### ISSUE TITLE
Driver app should poll for status during ride to detect cancel/reassign

### ISSUE THREAD

**Issue by geraldhuff** [john/drive.vote#890]
Because dispatchers can cancel or reassign a ride even after if it has been accepted by a driver, the driver app should poll periodically to get driver status and confirm the ride is still active. If it disappears or changes, the driver should be notified. Note it could be possible for (a) the ride to go away or (b) a different ride to be assigned in waiting_acceptance state.

**Comment by john** [comment]
@mcamis yeah might as well, should be straightforward right?

Funny picking up a conversation midstream that ended 21 months ago :-)
