### ISSUE TITLE
Pick a production deployment strategy

### ISSUE THREAD

**Issue by john** [john/drive.vote#905]
Possibilities (non-exclusive):
- Stick with AWS Elastic Beanstalk
- Move to standard Rails Heroku
- Move to containers on Heroku
- Move to containers using AWS Elastic Container Service (ECS)
- Move to AWS Fargate, a managed version of ECS

**Comment by awong-dev** [comment]
Thinking the right setup is sticking with AWS Elastic Beanstalk deploying with a container.

I'm uncertain what benefit there is to using the other services?

**Comment by john** [comment]
I think the benefits come at scale, when you have lots of containers to manage. But since I presume we'll use RDS and Elasticache in production rather than the Postgres and Redis containers that are part of the dev docker-compose, we just have one, basically.

So I'll take the liberty of closing this then, and replace it with #924.
