### ISSUE TITLE
Fix Google maps on Dispatcher pages

### ISSUE THREAD

**Issue by john** [john/drive.vote#915]
JS errors, despite having a GOOGLE_API_KEY value in .env. Related to but different than #912

**Comment by john** [comment]
Hi @wboykinm, thanks and thats helpful--saw that last night too and added a cc to my local account, and will use the Ragtag key in staging/prod. Turned out the updated API also created name conflicts with our own code; when rectified, and the updated API key used, it was fixed. Will get into master when #919 is merged.

**Comment by john** [comment]
And just added you as a collaborator in case you want to review the PR :-)

**Comment by messick** [comment]
@John with all the talk about getting Google Maps API stuff working again, I noticed you specifically configured Geocoder to not use Google anymore and go to the default provider, which happens to be Open Streets Map.

Besides requiring redoing all the recording API transitions for VCR, the data is different enough that all kinds of "require this address is inside this location" validations now fail in the tests.

Do you really mean to disable it?

**Comment by wboykinm** [comment]
. . . and boy do I hate to say this, but no OSM-based geocoding solution has really proved to be the equal of google, especially for mission-critical stuff like this.

**Comment by john** [comment]
Yeah agreed on all that, turning off Google for geocoding was a temp thing while I sorted out the API keys.

Right now it's using Google, but I don't think it's using a key--which I think means we'll have to worry about rate limits. So we should set up the Ragtag key soon. But that's a different issue, so I'm going to close this one :-)
