### ISSUE TITLE
In scheduled ride form, pre-populate city_for_pickup from Ride Zone

### ISSUE THREAD

**Issue by john** [john/drive.vote#917]
And if the user edits city_for_pickup, simultaneously edit input for city_for_pickup near the 'where_to_be_dropped_off'

Also, verify that we want the same input name in both places, I expected to see a city_for_dropoff field, or something like that. Two form elements with the same name is invalid HTML and could cause bugs.

**Comment by murdzaj** [comment]
Should city_for_dropoff be pre-populated also or only when city_for_pickup is edited?

**Comment by john** [comment]
This actually turned out to be confusing behavior, filing a ticket to revert. Entirely my bad call.
