### ISSUE TITLE
Fix styles on driver icons to not clash with new GMaps styles

### ISSUE THREAD

**Issue by john** [john/drive.vote#921]
Google changed the colors of their tiles, so some of our driver icons are darn near impossible to see. 
<img width="677" alt="screen shot 2018-08-24 at 9 58 58 am" src="https://user-images.githubusercontent.com/1668/44598230-29e38400-a787-11e8-9b43-5b209da6c4fc.png">

**Comment by dryan** [comment]
Might I suggest using https://mapstyle.withgoogle.com/, starting with the Silver theme and then turning off some of the map features that aren't useful in our context (we don't really need vegetation for instance).

**Comment by jamesarosen** [comment]
The SVGs in the repo don't seem like they match up to any of the driver or rider PNG icons. Do we have the SVGs that generated those?

**Comment by john** [comment]
@jamesarosen Not to my knowledge, though they might be buried in git somewhere.

On a whim I just plugged the styles generated by the link @dryan suggested above (using 'Silver') into dispatch_map.js.erb, and to my eye it's a big improvement, and Good Enough®. Check the image below, if you think that works maybe we go that route--I have it working locally, if you want to reassign to me I'll submit a PR for your approval.

<img width="1056" alt="screen shot 2018-09-05 at 12 04 55 am" src="https://user-images.githubusercontent.com/1668/45076784-2f529f80-b0a0-11e8-9b06-f9f0c9464ab6.png">

**Comment by dryan** [comment]
I think it looks great fwiw
