### ISSUE TITLE
Decide how to handle return rides for scheduled rides.

### ISSUE THREAD

**Issue by john** [john/drive.vote#925]
Voters who enter the system through scheduled rides won't be familiar with or know about the SMS interface. With that, we expected voters to send a second text requesting a ride ride home (or to work etc) after having voted. With scheduled rides, should we expect the driver to remain at the polling place until voting is done? Is that how this has traditionally been handled with ad hoc rides to polls?

Ask drivers how it was handled in '16 (I think a lot of drivers just did this), and talk to Brady, Malik, and others.

Related: #869

**Comment by john** [comment]
Related: #869

**Comment by john** [comment]
Training:
- Try to wait for them
- Suggest they text the ride zone sms number if the driver can't wait
- Question: do we support a voice number if the driver doesn't wait, and they don't have a phone?
- Make sure people aren't abandoned

**Comment by dryan** [comment]
Can we close this as a training issue and not a code issue?

**Comment by john** [comment]
@dryan: yes :-)
