### ISSUE TITLE
Collect license plate of drivers

### ISSUE THREAD

**Issue by john** [john/drive.vote#934]
And make of vehicle, send to voter in a notification before ride arrives.

**Comment by john** [comment]
Should we collect their driver's license too?

**Comment by john** [comment]
Need to add a migration to the User object to include license_plate (and drivers_licence?), then edit the form at this path to include it: /volunteer/san_francisco (san_francisco = ride zone slug)

**Comment by jamesarosen** [comment]
> Should we collect their driver's license too?

That depends on the purpose. Ride-share applications collect license plate, make, and model and send those to the rider so they can easily spot the car. DL doesn't help the rider spot the car. If there's another use-case, then possibly. But if not, it's just PII that serves to add risk to the system.

**Comment by john** [comment]
Closed by #945
