### ISSUE TITLE
 Create guide for admins

### ISSUE THREAD

**Issue by john** [john/drive.vote#950]
Third in priority after Driver & Dispatcher, can be shorter, things to cover:
- How to create drivers
- How to create dispatchers
- Requirements for training drivers & dispatchers, drivers in particular. We should be strict about this.
- How to bulk upload voters (could be delegated by an admin, but I think the admin guide is the natural place this would live)
- Drive the Vote staff to contact with questions or in case of emergency

**Comment by smarbin** [comment]
Barebones Draft [here](https://docs.google.com/document/d/1edDteeYMAE9wMUhcpklIory2a-he8WPADHfD5-Yzslk/edit#)
