### ISSUE TITLE
Set up cron job for scheduled rides

### ISSUE THREAD

**Issue by john** [john/drive.vote#966]
At the root of our app there's a file called cron.yml, which is used by Elastic Beanstalk. You can see this endpoint is being called every minute:
/api/1/rides/confirm_scheduled

We need a mechanism to POST to that URL every minute, or to set up a recurring job to do the same, which that calls the very simple method behind that endpoint:

    def confirm_scheduled
      Ride.confirm_scheduled_rides
      render text: 'ok'
    end

You can't run cron jobs Heroku. They offer a [free scheduling add-on](https://elements.heroku.com/addons/scheduler), but the won't schedule at any less than 10 minute intervals. One option is to set up a job which calls that method, and set up Sidekiq to run it. There's a Sidekiq plug in to do cron-like jobs:
https://github.com/ondrejbartas/sidekiq-cron

We could also set up a cron job somewhere else (AWS?) that just posts to that URL every minute, which might be the simplest thing. Or use a service like [SetCronJob](https://www.setcronjob.com/).

Right now emails are being sent inline, which isn't ideal--setting up Sidekiq would also give us the benefit of making those async. But we're down to the short strokes, so if you want to skip Sidekiq and do something simpler, if we can, your call.

**Comment by dryan** [comment]
I'm getting 404 on staging.drive.vote testing this URL
