### ISSUE TITLE
Update "Who made it" on www.drive.vote/about

### ISSUE THREAD

**Issue by smarbin** [john/drive.vote#978]
https://www.drive.vote/about

Update this text:
Who made it?
Drive the Vote is a DevProgress production. Please send questions, comments, suggestions to hello@drive.vote. Thanks!

To something like this:
Drive the Vote is produced by Ragtag, a team of tech volunteers who help activists, organizers, non-profits, and candidates break down tech barriers making it easier to achieve their organizing goals. Learn more at Ragtag.org. 
Drive the Vote was originally made by DevProgress and used in the 2016 elections in 3 cities. 
Please send questions, comments, suggestions to hello@drive.vote.

**Comment by john** [comment]
done, in prod
