### ISSUE TITLE
Flip order of rides in 'Inactive,' most recent up top

### ISSUE THREAD

**Issue by john** [john/drive.vote#987]
<img width="869" alt="screen shot 2018-09-19 at 3 57 58 pm" src="https://user-images.githubusercontent.com/1668/45786397-2546aa00-bc25-11e8-823f-3fe3512d301b.png">

**Comment by bengm** [comment]
Should that sort order be the same for all tabs?

It appears that time is the [timestamp/last_message_time](https://github.com/john/drive.vote/blob/master/app/assets/javascripts/dispatch.js.erb#L239).

**Comment by cgrayson** [comment]
Took a stab at this in that PR 👆  on the assumption it was indeed meant to only be for 'Inactive' rides. Let me know if that's incorrect, or if there's a better way to approach this!
